### ISSUE TITLE
Error: Invalid JSON response from Salesforce

### ISSUE THREAD

**Issue by Laboratory** [kevinohara80/nforce#102]
Hello, how can I catch this error and do resend request without crash (restart) application?

`````bash
W20151123-14:24:35.774(3)? (STDERR) Error: Invalid JSON response from Salesforce
W20151123-14:24:35.774(3)? (STDERR)     at Object.module.exports.invalidJson (/var/www/weapps/Chamaeleontis/.meteor/local/isopacks/veeam_nforce-sync/npm/node_modules/nforce/lib/errors.js:8:12)
W20151123-14:24:35.775(3)? (STDERR)     at processResponse (/var/www/weapps/Chamaeleontis/.meteor/local/isopacks/veeam_nforce-sync/npm/node_modules/nforce/index.js:973:43)
W20151123-14:24:35.775(3)? (STDERR)     at Request._callback (/var/www/weapps/Chamaeleontis/.meteor/local/isopacks/veeam_nforce-sync/npm/node_modules/nforce/index.js:1044:7)
W20151123-14:24:35.775(3)? (STDERR)     at Request.self.callback (/var/www/weapps/Chamaeleontis/.meteor/local/isopacks/veeam_nforce-sync/npm/node_modules/nforce/node_modules/request/request.js:198:22)
W20151123-14:24:35.775(3)? (STDERR)     at Request.emit (events.js:98:17)
W20151123-14:24:35.775(3)? (STDERR)     at Request.<anonymous> (/var/www/weapps/Chamaeleontis/.meteor/local/isopacks/veeam_nforce-sync/npm/node_modules/nforce/node_modules/request/request.js:1082:10)
W20151123-14:24:35.775(3)? (STDERR)     at Request.emit (events.js:117:20)
W20151123-14:24:35.776(3)? (STDERR)     at IncomingMessage.<anonymous> (/var/www/weapps/Chamaeleontis/.meteor/local/isopacks/veeam_nforce-sync/npm/node_modules/nforce/node_modules/request/request.js:1009:12)
W20151123-14:24:35.776(3)? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20151123-14:24:35.777(3)? (STDERR)     at _stream_readable.js:944:16
W20151123-14:24:35.777(3)? (STDERR)     at process._tickCallback (node.js:442:13)
`````
V

**Comment by kevinohara80** [comment]
To help, I'd need a little more context. Can you share your code where you are calling nforce?

If you are using the promises api, make sure you are adding a `.catch()` to your promise chain.

**Comment by kevinohara80** [comment]
Please re-open if you still need help.
