### ISSUE TITLE
Autorefresh isn't working

### ISSUE THREAD

**Issue by alexleventer** [kevinohara80/nforce#119]
I can't seem to get autorefresh working - what am I doing wrong?

Node v6.0.0
Nforce v1.5.0 
```js
var request = require('request');
var db = require('../database.js');
var _ = require('underscore');
var nforce = require('nforce');
var connection = db.getConnection();

/* Salesforce oauth settings */
var org = nforce.createConnection({
  clientId: process.env.SF_CLIENT || "token",
  clientSecret: process.env.SF_SECRET || "secret",
  redirectUri: process.env.SF_REDIRECT_URI || "http://localhost:3000/salesforce/callback",
  apiVersion: "v27.0",
  environment: "production",
  mode: "multi",
  autoRefresh: true,
  onRefresh: function(newOauth, oldOauth, callback) {
    connection.query("select * from integrations where salesforce=?",oldOauth.access_token, function(err,rows,fields) {
      var email = rows[0].email;
      connection.query("update integrations set salesforce=? where email=?",[newOauth.access_token, email], function(err,rows,fields){
        callback();
      })
    })
  }
});

exports.checkLeadInSalesforce = function(req, res) {
  var userEmail = req.query.useremail;
  var firstName = req.query.firstname;
  var lastName = req.query.lastname;

  connection.query('select * from integrations where email=?',[userEmail], function(err, rows, fields) {
    if (!!err) {
      console.log(err);
    } else {
      if (rows.length != 0) {
         var oauth = {
          access_token: rows[0].salesforce,
          refresh_token: rows[0].sf_refresh_token,
          signature: rows[0].sf_signature,
          instance_url: rows[0].sf_url,
          issued_at: rows[0].sf_issued_at,
          id: rows[0].sf_id,
          token_type: 'Bearer',
          scope: 'refresh_token web api id',
        };
        console.log('old token: ' + oauth.access_token);
        org.search({
          search: "FIND {" + firstName + " " + lastName + "} IN ALL FIELDS RETURNING Lead(Id, Name, Email)",
          oauth: oauth
        }, function(err, response) {
          if(!err){
            if (response.length === 0) {
              res.send({"found": false});
            } else {
              connection.query("update integrations set salesforce=? where email=?",[oauth.access_token, userEmail], function(err,rows,fields){
              });
              res.send({
                "found": true,
                "name": response[0].Name,
                "id": response[0].Id,
                "email": response[0].Email,
                "url": oauth.instance_url + "/" + response[0].Id
              });
            }
          }else{
            console.log(err);
          }
        });
      }
    }
  });
};

```

**Comment by kevinohara80** [comment]
Not really sure. Are you getting an error?

One thing I noticed is that you're trying to query in your `onRefresh()` callback using the `oldOauth` property. That oauth is expired and only passed in for reference purposes. `newOAuth` is what you need to use.

Furthermore, you don't need to manually run your query again inside of the `onRefresh()` method. `nforce` automatically re-tries your request for you. The `onRefresh` method is typically used for updating a database with the refreshed credentials.

Example here: https://github.com/kevinohara80/nforce/blob/master/examples/autorefresh-un.js

**Comment by alexleventer** [comment]
I'm get an expired token error from Salesforce whenever I try to run the query @kevinohara80. When I throw console logs into onRefresh, I'm not even seeing that being called.

**Comment by alexleventer** [comment]
```{ Error: invalid_grant - token validity expired
    at Request._callback (/Users/Alex/ws/src/salesdrive-web-app/node_modules/nforce/index.js:874:15)
    at Request.self.callback (/Users/Alex/ws/src/salesdrive-web-app/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/Alex/ws/src/salesdrive-web-app/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/Alex/ws/src/salesdrive-web-app/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) statusCode: 400 }
```

**Comment by alexleventer** [comment]
The problem was w/ my Salesforce application refresh_token settings. As soon as I changed my refresh token settings - onRefresh was called: ![Alt text](https://monosnap.com/file/sOWzQvOzO5o9jVSHWlMiIbNzptuEGD.png)

Closing this issue.
