### ISSUE TITLE
sObject.set forcing keys to be lowercase

### ISSUE THREAD

**Issue by ReeSilva** [kevinohara80/nforce#135]
Hey @kevinohara80 , hope you've been doing well.

When I use .set in a sObject, they force my field name to be lowercase, and this is not the standard in my Salesforce API names.

Even if I set the _fields object with key with the first letter in uppercase (this is my standard), when I call the .insert method it try to send the object with lowercase keys.

How can I avoid this situation?

Thanks in advance.

Example of return and the object:
```
{ Error: No such column 'date__c' on sobject of type BR_CP_Account__c
    at processResponse (/home/renato/Projects/carlos/node_modules/nforce/index.js:1022:13)
    at Request._callback (/home/renato/Projects/carlos/node_modules/nforce/index.js:1069:7)
    at Request.self.callback (/home/renato/Projects/carlos/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/renato/Projects/carlos/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/renato/Projects/carlos/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
  errorCode: 'INVALID_FIELD',
  body: 
   [ { message: 'No such column \'date__c\' on sobject of type BR_CP_Account__c',
       errorCode: 'INVALID_FIELD' } ],
  statusCode: 400 } 'Error: No such column \'date__c\' on sobject of type BR_CP_Account__c\n    at processResponse (/home/renato/Projects/carlos/node_modules/nforce/index.js:1022:13)\n    at Request._callback (/home/renato/Projects/carlos/node_modules/nforce/index.js:1069:7)\n    at Request.self.callback (/home/renato/Projects/carlos/node_modules/request/request.js:188:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (/home/renato/Projects/carlos/node_modules/request/request.js:1171:10)\n    at emitOne (events.js:96:13)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (/home/renato/Projects/carlos/node_modules/request/request.js:1091:12)\n    at IncomingMessage.g (events.js:292:16)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:80:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)'
> console.log(report);
Record {
  attributes: { type: 'BR_CP_Account__c' },
  _changed: [ 'name' ],
  _previous: { name: undefined },
  _fields: { name: 'Teste report pela API', Date__c: '2017-07-19' } }
```

**Comment by ReeSilva** [comment]
I've open a pull request that adds a parameter to record.set to say if the function must keeps the case or set it to lower.

It was a simple change because I have hurry. I don't know if it can cause some issues on the module, but I have runned npm test and everything is ok.

Regards.

**Comment by kevinohara80** [comment]
Salesforce is in general, case insensitive so the error above wouldn't be because of the lowercasing of the property names. I'm going to close this one for now.
