### ISSUE TITLE
getting EPROTO on OAUTH authentication 

### ISSUE THREAD

**Issue by ahmed-anas** [kevinohara80/nforce#156]
Hey guys,

Trying to integrate this package with oauth (web based) but I'm getting an EPROTO error. Here is the code:

Node version 7.8.0. 

```

var nforce = require('nforce');

var org = nforce.createConnection({
    clientId: 'CLIENT_ID_REMOVED',
    clientSecret: 'CLIENT_SECRET_REMOVED',
    redirectUri: 'http://localhost:3000/salesforce/oauth-callback',
});

router.get('/auth/sfdc', function (req, res) {
    res.redirect(org.getAuthUri());
});

router.get('/salesforce/oauth-callback', function (req, res) {
    console.log(req.query.code);
    org.authenticate({ code: req.query.code }, function (err, resp) {
        console.log(err, resp); //EPROTO error here
    });
});
```

It authenticates fine and redirects me, but the org.authenticate method returns an EPROTO error. 

Error:

```
Error: write EPROTO 101057795:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:openssl\ssl\s3_pkt.c:1498:SSL alert number 40
101057795:error:1409E0E5:SSL routines:ssl3_write_bytes:ssl handshake failure:openssl\ssl\s3_pkt.c:659:

    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

**Comment by kevinohara80** [comment]
I can't tell what's going on here but my suspicion is that it's something to do with your server's SSL configuration.

**Comment by ahmed-anas** [comment]
Yes. It was a code issue. Closing.
