### ISSUE TITLE
Crash application when json parsing

### ISSUE THREAD

**Issue by Laboratory** [kevinohara80/nforce#85]
Application should not crash in this solution.

`````bash
W20150410-02:31:02.069(3)? (STDERR) Error: Invalid JSON response from Salesforce
W20150410-02:31:02.069(3)? (STDERR)     at Object.module.exports.invalidJson (/Users/Laboratory/tmp/db/meteor/av/meteor-app/.meteor/local/isopacks/_nforce-sync/npm/node_modules/nforce/lib/errors.js:8:12)
W20150410-02:31:02.069(3)? (STDERR)     at processResponse (/Users/Laboratory/tmp/db/meteor/av/meteor-app/.meteor/local/isopacks/_nforce-sync/npm/node_modules/nforce/index.js:939:43)
W20150410-02:31:02.070(3)? (STDERR)     at Request._callback (/Users/Laboratory/tmp/db/meteor/av/meteor-app/.meteor/local/isopacks/_nforce-sync/npm/node_modules/nforce/index.js:1010:7)
W20150410-02:31:02.070(3)? (STDERR)     at Request.self.callback (/Users/Laboratory/tmp/db/meteor/av/meteor-app/.meteor/local/isopacks/_nforce-sync/npm/node_modules/nforce/node_modules/request/request.js:368:22)
W20150410-02:31:02.070(3)? (STDERR)     at Request.emit (events.js:98:17)
W20150410-02:31:02.070(3)? (STDERR)     at Request.<anonymous> (/Users/Laboratory/tmp/db/meteor/av/meteor-app/.meteor/local/isopacks/_nforce-sync/npm/node_modules/nforce/node_modules/request/request.js:1219:14)
W20150410-02:31:02.070(3)? (STDERR)     at Request.emit (events.js:117:20)
W20150410-02:31:02.070(3)? (STDERR)     at IncomingMessage.<anonymous> (/Users/Laboratory/tmp/db/meteor/av/meteor-app/.meteor/local/isopacks/_nforce-sync/npm/node_modules/nforce/node_modules/request/request.js:1167:12)
W20150410-02:31:02.070(3)? (STDERR)     at IncomingMessage.emit (events.js:117:20)
W20150410-02:31:02.070(3)? (STDERR)     at _stream_readable.js:943:16
W20150410-02:31:02.071(3)? (STDERR)     at process._tickCallback (node.js:419:13)
I20150410-02:31:05.366(3)? mongodb://localhost:3002/meteor connect
=> Meteor server restarted
`````

**Comment by kevinohara80** [comment]
Not sure I can help here without some additional context. 

Also, that error is a returned (not thrown) error that arises when Salesforce returns an invalid json response which happens in some edge case scenarios. Not sure why a callback with an error would crash your app but it's hard to say without seeing any of the code.

**Comment by kevinohara80** [comment]
If you are still having issues and can provide some context and code, feel free to re-open the issue
