### ISSUE TITLE
Weird net connection exception in unit test

### ISSUE THREAD

**Issue by kevinohara80** [kevinohara80/nforce#94]
For some reason I think the mock api server is throwing network connection errors. It never causes any of the unit tests to fail but it's muddying up the test results. See  below.

## Example

```
promises
    #getIdentity
  ✓ should not return a promise with a callback 
  ✓ should return a promise with no callback 
Unhandled rejection Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
    #getVersions
  ✓ should not return a promise with a callback 
  ✓ should return a promise with no callback 
    #insert
  ✓ should not return a promise with a callback 
  ✓ should return a promise with no callback 
    #update
  ✓ should not return a promise with a callback 
  ✓ should return a promise with no callback 
```

**Comment by pentode** [comment]
I think this is line 94 in test/mock/sfdc-rest-api.js
```
    id: 'http://localhost: ' + port + '/id/00Dd0000000fOlWEAU/005d00000014XTPAA2',
```
should be (without the space after the colon)
```
    id: 'http://localhost:' + port + '/id/00Dd0000000fOlWEAU/005d00000014XTPAA2',
```
